In [ ]:
# Classes and objects

    '''Example-01: Class and objects'''
    
class human:
    def __init__(self,name,occu):    
        self.name=name
        self.occu=occu
        
    def do_work(self): 
        if self.occu=="tennis player" :
            print(self.name, "plays tennis") 
            
        elif self.occu=="actor":
            print(self.name,"shoot film")
            
    def speaks(self):
        
        print(self.name, "says how are you?")
        
tom=human("tom","actor")
tom.do_work()
tom.speaks()

maria=human("Maria","tennis player")
maria.do_work()
maria.speaks()
            

# Libraries to be imported

In [2]:
# Import Libraries

import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
import cv2
import pandas as pd
import skimage.io as io
import seaborn as se

# Command to install the libraries

In [1]:
conda install -c conda-forge seaborn

SyntaxError: invalid syntax (<ipython-input-1-9c21f5807c5a>, line 1)

# Numpy

In [11]:
#Convert list to numpy array
mylist=[[1,2,3],[4,5,6]]
arr=np.asarray(mylist)
print (arr)
print(type(arr))
print(type(mylist))
print(arr.shape)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
<class 'list'>
(2, 3)
int32


In [15]:
#Create a numpy array
arr1=np.array([[4,5],[6,7],[8,9]])
print (arr1)
print(type(arr1))
print((arr1.dtype))
print(arr1.shape)

[[4 5]
 [6 7]
 [8 9]]
<class 'numpy.ndarray'>
int32
(3, 2)


In [20]:
arr0=np.zeros((50,6),dtype='float64')
print(arr0.shape,arr0.dtype)
print(arr0[3][3])

(50, 6) float64
0.0


In [21]:
print (arr0[1][:])

[ 0.  0.  0.  0.  0.  0.]


In [22]:
arr1=np.ones((4,4))
print(arr1)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [23]:
print(arr1.shape)

(4, 4)


In [27]:
print(arr1.sum()) # Total sum

16.0


In [42]:
print(sum(arr1[0:5])) # row-wise sum

[ 4.  4.  4.  4.]


In [9]:
# Create Identity Matrix
I=np.eye(4)
print (I,I.shape)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]] (4, 4)


In [11]:
# Copy array
arr1=I
arr2=arr1.copy()
print (arr2.shape)
print (arr2)

(4, 4)
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [21]:
# Changing the shape of array
arr3=arr2.reshape((16,1))
arr4=arr2.reshape(2,-1)
print (arr3.shape)
print (arr4.shape)

(16, 1)
(2, 8)


In [30]:
# Random arrays
a=np.random.random((3,4))
print (a)
b=np.random.randint(4,6,(2,2))
print (b)

[[ 0.75282589  0.260064    0.30321365  0.47289602]
 [ 0.92920846  0.66007945  0.81153825  0.41900615]
 [ 0.23195021  0.80114799  0.46647442  0.11833367]]
[[4 5]
 [4 4]]


In [32]:
#  Mean of array
print (b.mean())
print (b[0].mean())
print (b[:][0].mean())

4.25
4.5
4.5


In [33]:
# Transpose of matrix
c=b.T
print (c)

[[4 4]
 [5 4]]


In [40]:
# Concatenate matrices
a1=np.zeros((4,4))
a2=np.ones((4,3))
a3=np.concatenate((a1,a2),axis=1)

print(a1)
print(a2)
print(a3)


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 0.  0.  0.  0.  1.  1.  1.]
 [ 0.  0.  0.  0.  1.  1.  1.]
 [ 0.  0.  0.  0.  1.  1.  1.]
 [ 0.  0.  0.  0.  1.  1.  1.]]


In [42]:
# Calculate invesre of a matrix
a2_inv=np.linalg.pinv(a2)

print(a2_inv)

[[ 0.08333333  0.08333333  0.08333333  0.08333333]
 [ 0.08333333  0.08333333  0.08333333  0.08333333]
 [ 0.08333333  0.08333333  0.08333333  0.08333333]]


In [45]:
# Matrix multiplication
a=np.array([[2,3],[3,2]])
b=np.array([[3,5,6],[4,6,6]])
c=a.dot(b)
print (c,c.shape)

[[18 28 30]
 [17 27 30]] (2, 3)


In [48]:
# Element wise Multiplication
a1=np.array([[2,3],[3,2]])
b1=np.array([[3,5],[4,6]])
c1=a1*b1
print(a1)
print(b1)
print ((c1),c1.shape)

[[2 3]
 [3 2]]
[[3 5]
 [4 6]]


TypeError: only length-1 arrays can be converted to Python scalars

In [49]:
c1=c1.astype(float)
print (c1)

[[  6.  15.]
 [ 12.  12.]]


In [50]:
# Concatenate and reshape
a=np.array([[2,3],[3,2]])
b=np.array([[3,5,6],[4,6,6]])
c=np.concatenate((a,b.reshape(-1,2)),axis=0)
print (c,c.shape)

[[2 3]
 [3 2]
 [3 5]
 [6 4]
 [6 6]] (5, 2)


# Lambda, Map and Filtering

In [34]:
# Lambda function 
a=[1,2,3,4]
t= filter(lambda x: x>2,a)
print (list(t))

# Mapping function
y=map(lambda x:x**2,a)

print(list(y))



[3, 4]
[1, 4, 9, 16]


# Generator function

In [36]:
def add(x,y,z):
    yield x+y
    yield x+z
    yield y+z
    
print (list(add(1,2,3))) 

[3, 4, 5]
